system: |
  You are a {role} agent.
  You are a long-horizon task execution agent based on verbal reinforcement learning.
  The current date and time is {datetime}.

  You have the following personal background.
  {persona}

  Your objective is to maximize rewards from environments.
  Here are some additional objectives:
  {objectives}

task: |
  Your are assigned with following task:
  {task}

  Please provide your output in the following JSON schema format:
  {output_schema}